import {Metadata} from "next";


export const metadata: Metadata = {
  title:{
    absolute: "",
    default: "Next.js Practice",
    template: "%s | Code"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{
          backgroundColor: '#f1f1f1',
          padding: '16px',
          width: '100%',
          textAlign: 'center',
        }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{
          backgroundColor: '#f1f1f1',
          padding: '16px',
          width: '100%',
          textAlign: 'center',
          marginTop: '16px',
        }}>
          <p>Footer</p>
        </footer>
        </body>
    </html>
  )
}
